import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "es" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    appTitle: "Bot Templates",
    navHome: "Home",
    navTelegram: "Telegram Bots",
    navWhatsApp: "WhatsApp Bots",
    navSetup: "Setup Guide",
    navTips: "Best Practices",
    navDeploy: "24/7 Deployment",
    navCredentials: "Credentials",
    navAdmin: "Admin Panel",
    navErrors: "Common Errors",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    langToggle: "ES",
    languageLabel: "Language",
    loggedAs: "Signed in as",
    logoutButton: "Sign out",
    loadingSession: "Loading session...",

    controlsTitle: "Display controls",
    brightness: "Brightness",
    brightnessHint: "Dim the screen to reduce glare. Min 30% — max 100%.",

    loginTitle: "Sign in to the panel",
    loginSubtitle: "Local-only admin panel. Manage your bot tokens and templates from one place.",
    loginUsername: "Username",
    loginPassword: "Password",
    loginButton: "Sign in",
    loginLoading: "Working...",
    loginInvalid: "Invalid username or password.",
    loginLocked: "Account is locked.",
    loginNoCreds: "No credentials configured. Check the API server logs.",
    loginFirstHint: "On first run the API server creates an 'admin' user and prints the initial password to its console. Change it from the Admin Panel after signing in.",

    adminTitle: "Admin Panel",
    adminSubtitle: "Manage your local panel account, rotate the password, and configure the bot tokens used by every template.",
    adminAccountTitle: "Account",
    adminAccountUser: "User",
    adminAccountId: "Credential ID",
    adminAccountCreated: "Created",
    adminAccountUpdated: "Updated",
    adminLockTitle: "Lock account",
    adminLockHint: "While locked, sign in is rejected. Useful while the panel is unattended.",

    adminPwdTitle: "Change password",
    adminPwdRotateHint: "Each password change generates a new credential ID and renames the file on disk; existing connection data is preserved.",
    adminPwdCurrent: "Current password",
    adminPwdNew: "New password (min 8 chars)",
    adminPwdConfirm: "Confirm new password",
    adminPwdGenerate: "Generate strong password",
    adminPwdSave: "Save new password",
    adminPwdChanged: "Password updated and credential file rotated.",
    adminPwdMismatch: "Passwords do not match.",
    adminPwdWeak: "Password must be at least 8 characters.",
    adminPwdInvalidCurrent: "Current password is incorrect.",
    adminPwdFailed: "Could not update the password.",

    adminTokensTitle: "Bot tokens",
    adminTokensSubtitle: "Saved to data/tokens.json and synced to the project .env so bots pick them up automatically.",
    adminTokensReveal: "Reveal",
    adminTokensHide: "Hide",
    adminTokensSave: "Save tokens",
    adminTokensSaved: "Tokens saved and .env file updated.",
    adminTokensError: "Could not save tokens.",
    adminTokensFootnote: "Values are stored locally only — they never leave your machine.",

    tokTelegramBot: "Telegram bot token (BotFather)",
    tokTelegramOwner: "Telegram owner ID",
    tokWaApiKey: "WhatsApp API key",
    tokWaPhone: "WhatsApp phone number ID",
    tokWaVerify: "WhatsApp verify token",
    tokWaAccess: "WhatsApp access token",
    tokOpenAi: "OpenAI API key",
    tokAnthropic: "Anthropic API key",
    tokGemini: "Gemini API key",

    homeTitle: "Python Bot Templates",
    homeSubtitle: "The fastest way to go from zero to a working Python bot. A developer's cheat sheet that respects your time.",
    homeTelegramTitle: "Telegram Bots",
    homeTelegramDesc: "Templates using the python-telegram-bot library.",
    homeWhatsAppTitle: "WhatsApp Bots",
    homeWhatsAppDesc: "Templates using Twilio API and Flask webhooks.",
    homeFeature1: "Basic Echo & Command bots",
    homeFeature2: "Inline Keyboards & Callbacks",
    homeFeature3: "File downloads & Polls",
    homeWaFeature1: "Flask Webhook integration",
    homeWaFeature2: "Media handling (Images/Docs)",
    homeWaFeature3: "OpenAI / ChatGPT integration",
    homeViewTelegram: "View Telegram Templates",
    homeViewWhatsApp: "View WhatsApp Templates",
    homeChecklist: "Quick Start Checklist",
    homeStep1Title: "1. Environment",
    homeStep1Desc: "Python 3.9+, pip, and an IDE. A virtual environment is highly recommended.",
    homeStep2Title: "2. Credentials",
    homeStep2Desc: "Telegram Bot Token from BotFather, or Twilio Account SID and Auth Token.",
    homeStep3Title: "3. Dependencies",
    homeStep3Desc: "Install the required packages using pip. Check the setup guide for specifics.",
    homeReadSetup: "Read the full setup guide",

    telegramTitle: "Telegram Bot Templates",
    telegramSubtitle: "Production-ready templates using the official python-telegram-bot library v20+. These use the modern async/await syntax.",

    whatsappTitle: "WhatsApp Bot Templates",
    whatsappSubtitle: "These templates use the Twilio Messaging API. Since WhatsApp requires business verification for native API access, Twilio is the standard developer path.",

    setupTitle: "Setup Guides",
    setupSubtitle: "Step-by-step instructions to get your development environment ready for bot building.",
    setupTelegramTitle: "Telegram Setup",
    setupWhatsAppTitle: "WhatsApp (Twilio) Setup",
    setupStep1: "1. Get a Bot Token",
    setupStep2: "2. Install Dependencies",
    setupStep3: "3. Requirements File",
    setupWaStep1: "1. Twilio Sandbox",
    setupWaStep2: "2. Expose Local Server",
    setupWaStep3: "3. Install Dependencies",
    setupWaStep4: "4. Requirements File",
    setupTelegramSteps: "Open Telegram and search for @BotFather|Send the command /newbot|Follow prompts to choose a name and username|BotFather will give you an HTTP API Token. Keep this secret!",
    setupWaSteps: "Create a free Twilio account|Go to Messaging > Try it out > Send a WhatsApp message|Follow instructions to join the Sandbox|Copy your Account SID and Auth Token from the console dashboard",

    tipsTitle: "Best Practices & Tips",
    tipsSubtitle: "Write robust, production-ready bot code.",
    tipsEnvTitle: "Environment Variables",
    tipsEnvDesc: "Never hardcode tokens or API keys in your Python files. Use a .env file and the python-dotenv package.",
    tipsLogTitle: "Logging",
    tipsLogDesc: "Use the built-in logging module instead of print() statements. It provides timestamps, log levels, and can write to files.",
    tipsDeployTitle: "Deployment Options",

    deployTitle: "24/7 Deployment",
    deploySubtitle: "Keep your bots running continuously. This guide covers local testing environments and cloud production setups.",
    deployLocalTitle: "Local Testing Environment",
    deployLocalDesc: "Run your bot on your own machine for development and testing. Everything stays local — no cloud costs.",
    deployCloudTitle: "Cloud Production (24/7)",
    deployCloudDesc: "Deploy to the cloud so your bot runs continuously without your computer being on. Ideal for paid production use.",
    deployDownloadTitle: "Download & Run Locally",
    deployDownloadDesc: "Use this setup to test your bot on your machine before going live.",
    deployProcfileTitle: "Procfile (for Railway/Render/Heroku)",
    deploySystemdTitle: "Linux Systemd Service (VPS)",
    deployDockerTitle: "Docker Container",
    deployRailwayTitle: "Railway (Recommended for Beginners)",
    deployRenderTitle: "Render",
    deployVpsTitle: "VPS with systemd",

    credTitle: "Credential Management",
    credSubtitle: "Your API tokens and keys must NEVER be hardcoded in your Python files. Here's how to manage them securely, both locally and in the cloud.",
    credLocalTitle: "Local Development (.env file)",
    credLocalDesc: "Store secrets in a .env file. This file should NEVER be committed to git.",
    credCloudTitle: "Cloud / Production (Environment Variables)",
    credCloudDesc: "In cloud platforms, set environment variables in their dashboard. Your code reads them the same way.",
    credGitignoreTitle: "Always add .env to .gitignore",
    credLoadTitle: "Loading credentials in Python",
    credRailwayTitle: "Railway / Render / Heroku",
    credVpsTitle: "VPS / Server",

    loginFirstRunTitle: "Initial setup credentials",
    loginFirstRunDesc: "Copy this password before continuing — it will not be shown again.",
    loginFirstRunUser: "Username:",
    loginFirstRunPass: "Initial password:",
    loginFirstRunCopy: "Copy password",
    loginFirstRunWarning: "Change this password from the Admin Panel after signing in.",
        modifyHint: "MODIFY",
    copyCode: "Copy Code",
    copied: "Copied",
    downloadCode: "Download file",
    searchPlaceholder: "Search templates...",
    searchNoResults: "No templates match your search.",
  },
  es: {
    appTitle: "Plantillas de Bots",
    navHome: "Inicio",
    navTelegram: "Bots Telegram",
    navWhatsApp: "Bots WhatsApp",
    navSetup: "Guía de Instalación",
    navTips: "Buenas Prácticas",
    navDeploy: "Despliegue 24/7",
    navCredentials: "Credenciales",
    navAdmin: "Panel Admin",
    navErrors: "Errores Comunes",
    lightMode: "Modo Claro",
    darkMode: "Modo Oscuro",
    langToggle: "EN",
    languageLabel: "Idioma",
    loggedAs: "Sesión iniciada como",
    logoutButton: "Cerrar sesión",
    loadingSession: "Cargando sesión...",

    controlsTitle: "Controles de pantalla",
    brightness: "Brillo",
    brightnessHint: "Atenúa la pantalla para reducir el brillo. Mín 30% — máx 100%.",

    loginTitle: "Ingresar al panel",
    loginSubtitle: "Panel de administración local. Gestioná los tokens y plantillas de tus bots desde un solo lugar.",
    loginUsername: "Usuario",
    loginPassword: "Contraseña",
    loginButton: "Ingresar",
    loginLoading: "Procesando...",
    loginInvalid: "Usuario o contraseña inválidos.",
    loginLocked: "La cuenta está bloqueada.",
    loginNoCreds: "No hay credenciales configuradas. Revisá los logs del servidor API.",
    loginFirstHint: "En el primer arranque el servidor API crea el usuario 'admin' y muestra la contraseña inicial en su consola. Cambiala desde el Panel Admin luego de ingresar.",

    adminTitle: "Panel de Administración",
    adminSubtitle: "Administrá la cuenta del panel local, rotá la contraseña y configurá los tokens de los bots que usan todas las plantillas.",
    adminAccountTitle: "Cuenta",
    adminAccountUser: "Usuario",
    adminAccountId: "ID de credencial",
    adminAccountCreated: "Creada",
    adminAccountUpdated: "Actualizada",
    adminLockTitle: "Bloquear cuenta",
    adminLockHint: "Mientras está bloqueada, no se permite iniciar sesión. Útil cuando el panel queda desatendido.",

    adminPwdTitle: "Cambiar contraseña",
    adminPwdRotateHint: "Cada cambio de contraseña genera un nuevo ID de credencial y renombra el archivo en disco; los datos de conexión se conservan.",
    adminPwdCurrent: "Contraseña actual",
    adminPwdNew: "Nueva contraseña (mín 8 caracteres)",
    adminPwdConfirm: "Confirmar nueva contraseña",
    adminPwdGenerate: "Generar contraseña fuerte",
    adminPwdSave: "Guardar nueva contraseña",
    adminPwdChanged: "Contraseña actualizada y archivo de credenciales rotado.",
    adminPwdMismatch: "Las contraseñas no coinciden.",
    adminPwdWeak: "La contraseña debe tener al menos 8 caracteres.",
    adminPwdInvalidCurrent: "La contraseña actual es incorrecta.",
    adminPwdFailed: "No se pudo actualizar la contraseña.",

    adminTokensTitle: "Tokens de los bots",
    adminTokensSubtitle: "Se guardan en data/tokens.json y se sincronizan al .env del proyecto para que los bots los tomen automáticamente.",
    adminTokensReveal: "Mostrar",
    adminTokensHide: "Ocultar",
    adminTokensSave: "Guardar tokens",
    adminTokensSaved: "Tokens guardados y archivo .env actualizado.",
    adminTokensError: "No se pudieron guardar los tokens.",
    adminTokensFootnote: "Los valores se almacenan solo localmente — nunca salen de tu máquina.",

    tokTelegramBot: "Token de bot de Telegram (BotFather)",
    tokTelegramOwner: "ID de dueño de Telegram",
    tokWaApiKey: "API key de WhatsApp",
    tokWaPhone: "Phone Number ID de WhatsApp",
    tokWaVerify: "Verify Token de WhatsApp",
    tokWaAccess: "Access Token de WhatsApp",
    tokOpenAi: "API key de OpenAI",
    tokAnthropic: "API key de Anthropic",
    tokGemini: "API key de Gemini",

    homeTitle: "Plantillas de Bots en Python",
    homeSubtitle: "La forma más rápida de pasar de cero a un bot funcional en Python. Una guía de referencia que respeta tu tiempo.",
    homeTelegramTitle: "Bots de Telegram",
    homeTelegramDesc: "Plantillas usando la librería python-telegram-bot.",
    homeWhatsAppTitle: "Bots de WhatsApp",
    homeWhatsAppDesc: "Plantillas usando la API de Twilio y webhooks con Flask.",
    homeFeature1: "Bots de eco y comandos básicos",
    homeFeature2: "Teclados inline y callbacks",
    homeFeature3: "Descarga de archivos y encuestas",
    homeWaFeature1: "Integración de webhook con Flask",
    homeWaFeature2: "Manejo de multimedia (Imágenes/Docs)",
    homeWaFeature3: "Integración con OpenAI / ChatGPT",
    homeViewTelegram: "Ver Plantillas de Telegram",
    homeViewWhatsApp: "Ver Plantillas de WhatsApp",
    homeChecklist: "Lista de Inicio Rápido",
    homeStep1Title: "1. Entorno",
    homeStep1Desc: "Python 3.9+, pip y un IDE. Se recomienda usar un entorno virtual.",
    homeStep2Title: "2. Credenciales",
    homeStep2Desc: "Token del Bot de Telegram desde BotFather, o Account SID y Auth Token de Twilio.",
    homeStep3Title: "3. Dependencias",
    homeStep3Desc: "Instala los paquetes necesarios con pip. Consulta la guía de instalación para más detalles.",
    homeReadSetup: "Leer la guía completa de instalación",

    telegramTitle: "Plantillas de Bots para Telegram",
    telegramSubtitle: "Plantillas listas para producción usando la librería oficial python-telegram-bot v20+. Usan sintaxis moderna async/await.",

    whatsappTitle: "Plantillas de Bots para WhatsApp",
    whatsappSubtitle: "Estas plantillas usan la API de Mensajería de Twilio. Como WhatsApp requiere verificación comercial para acceso nativo a la API, Twilio es el camino estándar para desarrolladores.",

    setupTitle: "Guías de Configuración",
    setupSubtitle: "Instrucciones paso a paso para preparar tu entorno de desarrollo para construir bots.",
    setupTelegramTitle: "Configuración de Telegram",
    setupWhatsAppTitle: "Configuración de WhatsApp (Twilio)",
    setupStep1: "1. Obtener un Token de Bot",
    setupStep2: "2. Instalar Dependencias",
    setupStep3: "3. Archivo de Requisitos",
    setupWaStep1: "1. Sandbox de Twilio",
    setupWaStep2: "2. Exponer el Servidor Local",
    setupWaStep3: "3. Instalar Dependencias",
    setupWaStep4: "4. Archivo de Requisitos",
    setupTelegramSteps: "Abre Telegram y busca @BotFather|Envía el comando /newbot|Sigue las instrucciones para elegir nombre y usuario|BotFather te dará un Token de API HTTP. ¡Mantenlo en secreto!",
    setupWaSteps: "Crea una cuenta gratuita de Twilio|Ve a Mensajería > Pruébalo > Envía un mensaje de WhatsApp|Sigue las instrucciones para unirte al Sandbox|Copia tu Account SID y Auth Token del panel de control",

    tipsTitle: "Buenas Prácticas y Consejos",
    tipsSubtitle: "Escribe código de bot robusto, listo para producción.",
    tipsEnvTitle: "Variables de Entorno",
    tipsEnvDesc: "Nunca escribas tokens o claves API directamente en tus archivos Python. Usa un archivo .env y el paquete python-dotenv.",
    tipsLogTitle: "Logging (Registros)",
    tipsLogDesc: "Usa el módulo logging integrado en lugar de sentencias print(). Proporciona marcas de tiempo, niveles de log y puede escribir en archivos.",
    tipsDeployTitle: "Opciones de Despliegue",

    deployTitle: "Despliegue 24/7",
    deploySubtitle: "Mantén tus bots corriendo continuamente. Esta guía cubre entornos de prueba local y configuraciones de producción en la nube.",
    deployLocalTitle: "Entorno de Prueba Local",
    deployLocalDesc: "Ejecuta tu bot en tu propia máquina para desarrollo y pruebas. Todo se mantiene local — sin costos en la nube.",
    deployCloudTitle: "Producción en la Nube (24/7)",
    deployCloudDesc: "Despliega en la nube para que tu bot corra continuamente sin necesidad de tener tu computadora encendida. Ideal para uso en producción de pago.",
    deployDownloadTitle: "Descargar y Ejecutar Localmente",
    deployDownloadDesc: "Usa esta configuración para probar tu bot en tu máquina antes de ponerlo en producción.",
    deployProcfileTitle: "Procfile (para Railway/Render/Heroku)",
    deploySystemdTitle: "Servicio Systemd de Linux (VPS)",
    deployDockerTitle: "Contenedor Docker",
    deployRailwayTitle: "Railway (Recomendado para Principiantes)",
    deployRenderTitle: "Render",
    deployVpsTitle: "VPS con systemd",

    credTitle: "Gestión de Credenciales",
    credSubtitle: "Tus tokens y claves API NUNCA deben estar escritos directamente en tus archivos Python. Aquí se explica cómo gestionarlos de forma segura, tanto localmente como en la nube.",
    credLocalTitle: "Desarrollo Local (archivo .env)",
    credLocalDesc: "Guarda los secretos en un archivo .env. Este archivo NUNCA debe subirse a git.",
    credCloudTitle: "Nube / Producción (Variables de Entorno)",
    credCloudDesc: "En plataformas en la nube, configura las variables de entorno en su panel de control. Tu código las lee de la misma forma.",
    credGitignoreTitle: "Siempre agrega .env a .gitignore",
    credLoadTitle: "Cargar credenciales en Python",
    credRailwayTitle: "Railway / Render / Heroku",
    credVpsTitle: "VPS / Servidor",

    loginFirstRunTitle: "Credenciales del primer arranque",
    loginFirstRunDesc: "Copiá la contraseña antes de continuar — no se volverá a mostrar.",
    loginFirstRunUser: "Usuario:",
    loginFirstRunPass: "Contraseña inicial:",
    loginFirstRunCopy: "Copiar contraseña",
    loginFirstRunWarning: "Cambiala desde el Panel Admin luego de ingresar.",
        modifyHint: "MODIFICAR",
    copyCode: "Copiar Código",
    copied: "Copiado",
    downloadCode: "Descargar archivo",
    searchPlaceholder: "Buscar plantillas...",
    searchNoResults: "Ninguna plantilla coincide con tu búsqueda.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "es",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem("lang") as Lang) || "es";
  });

  const updateLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string) => translations[lang][key] ?? translations["en"][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: updateLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
