// Catálogo estático de todas las plantillas de bots disponibles.
// Agregar nuevas entradas aquí cuando se agreguen nuevas plantillas.

export interface BotEntry {
  id: string;
  nameEs: string;
  nameEn: string;
  file: string;
  category: "telegram" | "whatsapp" | "ctf-osint" | "utility";
  descEs: string;
  descEn: string;
  commands: string[];
  envVars: string[];
  usageEs: string;
  usageEn: string;
  tags: string[];
}

export const BOT_CATALOG: BotEntry[] = [
  // ── TELEGRAM ─────────────────────────────────────────────
  {
    id: "tg_echo", nameEs: "Bot de Eco", nameEn: "Echo Bot",
    file: "bots/telegram/echo_bot.py", category: "telegram",
    descEs: "Repite todos los mensajes que recibe. Plantilla base para cualquier bot Telegram.",
    descEn: "Repeats every message it receives. Base template for any Telegram bot.",
    commands: ["/start", "/help"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Enviá cualquier mensaje al bot — responderá con el mismo texto.",
    usageEn: "Send any message to the bot — it replies with the same text.",
    tags: ["básico", "eco"],
  },
  {
    id: "tg_commands", nameEs: "Bot de Comandos", nameEn: "Commands Bot",
    file: "bots/telegram/commands_bot.py", category: "telegram",
    descEs: "Maneja comandos personalizados con manejadores separados.",
    descEn: "Handles custom commands with separate handlers.",
    commands: ["/start", "/help", "/info", "/ping"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /ping para verificar que el bot responde. /info muestra detalles del sistema.",
    usageEn: "Use /ping to verify the bot responds. /info shows system details.",
    tags: ["básico", "comandos"],
  },
  {
    id: "tg_inline", nameEs: "Teclado Inline", nameEn: "Inline Keyboard Bot",
    file: "bots/telegram/inline_keyboard_bot.py", category: "telegram",
    descEs: "Bot con botones inline interactivos y callbacks.",
    descEn: "Bot with interactive inline buttons and callbacks.",
    commands: ["/start", "/menu"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /menu para ver los botones inline.",
    usageEn: "Use /menu to see the inline buttons.",
    tags: ["básico", "inline", "teclado"],
  },
  {
    id: "tg_files", nameEs: "Bot de Archivos", nameEn: "Files Bot",
    file: "bots/telegram/files_bot.py", category: "telegram",
    descEs: "Descarga, sube y procesa archivos enviados por el usuario.",
    descEn: "Downloads, uploads and processes files sent by the user.",
    commands: ["/start", "/help"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Enviá una foto, documento o audio al bot.",
    usageEn: "Send a photo, document or audio to the bot.",
    tags: ["básico", "archivos", "media"],
  },
  {
    id: "tg_poll", nameEs: "Bot de Encuestas", nameEn: "Poll Bot",
    file: "bots/telegram/poll_bot.py", category: "telegram",
    descEs: "Crea y gestiona encuestas y quizzes interactivos.",
    descEn: "Creates and manages interactive polls and quizzes.",
    commands: ["/start", "/poll", "/quiz"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /poll para iniciar una encuesta, /quiz para un cuestionario.",
    usageEn: "Use /poll to start a survey, /quiz for a questionnaire.",
    tags: ["básico", "encuestas", "quiz"],
  },
  {
    id: "tg_group", nameEs: "Admin de Grupos", nameEn: "Group Admin Bot",
    file: "bots/telegram/group_admin_bot.py", category: "telegram",
    descEs: "Modera grupos: bienvenida, silencio, expulsión y registros.",
    descEn: "Moderates groups: welcome messages, mute, kick and logs.",
    commands: ["/start", "/mute", "/unmute", "/kick", "/warn"],
    envVars: ["TELEGRAM_BOT_TOKEN", "TELEGRAM_OWNER_ID"],
    usageEs: "Agregá el bot a un grupo como administrador.",
    usageEn: "Add the bot to a group as admin.",
    tags: ["grupo", "moderación", "admin"],
  },
  {
    id: "tg_scheduler", nameEs: "Bot Programador", nameEn: "Scheduler Bot",
    file: "bots/telegram/scheduler_bot.py", category: "telegram",
    descEs: "Envía mensajes programados y recordatorios automáticos.",
    descEn: "Sends scheduled messages and automatic reminders.",
    commands: ["/start", "/schedule", "/list", "/cancel"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /schedule <HH:MM> <mensaje> para programar un envío.",
    usageEn: "Use /schedule <HH:MM> <message> to schedule a send.",
    tags: ["programador", "cron", "recordatorios"],
  },
  {
    id: "tg_sqlite", nameEs: "Bot con SQLite", nameEn: "SQLite Bot",
    file: "bots/telegram/sqlite_bot.py", category: "telegram",
    descEs: "Persiste datos de usuarios en base de datos SQLite local.",
    descEn: "Persists user data in a local SQLite database.",
    commands: ["/start", "/save", "/get", "/list", "/delete"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /save <clave> <valor> para guardar datos.",
    usageEn: "Use /save <key> <value> to store data.",
    tags: ["sqlite", "base de datos", "persistencia"],
  },
  {
    id: "tg_conv", nameEs: "Conversación Multi-Paso", nameEn: "Conversation Handler Bot",
    file: "bots/telegram/conv_handler_bot.py", category: "telegram",
    descEs: "Implementa flujos de conversación con múltiples pasos y estados.",
    descEn: "Implements multi-step conversation flows with states.",
    commands: ["/start", "/register", "/cancel"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "Usá /register para iniciar el flujo de conversación multi-paso.",
    usageEn: "Use /register to start the multi-step conversation flow.",
    tags: ["conversación", "estados", "flujo"],
  },
  {
    id: "tg_agent_openai", nameEs: "Agente OpenAI", nameEn: "OpenAI Agent",
    file: "bots/telegram/agent_openai_basic.py", category: "telegram",
    descEs: "Agente IA usando GPT-4o con memoria de conversación y system prompt.",
    descEn: "AI agent using GPT-4o with conversation memory and system prompt.",
    commands: ["/start", "/reset", "/help"],
    envVars: ["TELEGRAM_BOT_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Escribí cualquier mensaje al bot — responde usando GPT-4o.",
    usageEn: "Send any message to the bot — it responds using GPT-4o.",
    tags: ["IA", "OpenAI", "GPT-4", "agente"],
  },
  {
    id: "tg_agent_anthropic", nameEs: "Agente Anthropic (Tools)", nameEn: "Anthropic Tools Agent",
    file: "bots/telegram/agent_anthropic_tools.py", category: "telegram",
    descEs: "Agente Claude con function calling: calculadora, clima y hora.",
    descEn: "Claude agent with function calling: calculator, weather and time.",
    commands: ["/start", "/reset"],
    envVars: ["TELEGRAM_BOT_TOKEN", "ANTHROPIC_API_KEY"],
    usageEs: "Preguntá 'Cuánto es 42 * 7?' o '¿Qué hora es?'",
    usageEn: "Ask 'What is 42 * 7?' or 'What time is it?'",
    tags: ["IA", "Anthropic", "Claude", "function calling"],
  },
  {
    id: "tg_agent_search", nameEs: "Agente con Búsqueda Web", nameEn: "Web Search Agent",
    file: "bots/telegram/agent_websearch.py", category: "telegram",
    descEs: "Agente que navega la web en tiempo real para responder preguntas.",
    descEn: "Agent that browses the web in real time to answer questions.",
    commands: ["/start", "/search <query>"],
    envVars: ["TELEGRAM_BOT_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Enviá /search <consulta> o preguntá directamente.",
    usageEn: "Send /search <query> or ask directly.",
    tags: ["IA", "búsqueda web", "OSINT ligero"],
  },
  {
    id: "tg_agent_vision", nameEs: "Agente de Visión", nameEn: "Vision Agent",
    file: "bots/telegram/agent_vision.py", category: "telegram",
    descEs: "Analiza imágenes usando GPT-4o Vision. Describe, extrae texto y más.",
    descEn: "Analyzes images using GPT-4o Vision. Describes, extracts text and more.",
    commands: ["/start", "/analyze"],
    envVars: ["TELEGRAM_BOT_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Enviá una imagen al bot para analizarla.",
    usageEn: "Send an image to the bot to analyze it.",
    tags: ["IA", "visión", "GPT-4o", "imágenes"],
  },
  {
    id: "tg_agent_rag", nameEs: "Agente RAG (Documentos)", nameEn: "RAG Document Agent",
    file: "bots/telegram/agent_rag_documents.py", category: "telegram",
    descEs: "Indexa documentos PDF/TXT y responde preguntas sobre ellos usando RAG.",
    descEn: "Indexes PDF/TXT documents and answers questions about them using RAG.",
    commands: ["/start", "/upload", "/ask <pregunta>", "/clear"],
    envVars: ["TELEGRAM_BOT_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Enviá un PDF con /upload, luego preguntá /ask <tu pregunta>.",
    usageEn: "Send a PDF with /upload, then ask /ask <your question>.",
    tags: ["IA", "RAG", "documentos", "PDF"],
  },
  // ── CTF / OSINT TELEGRAM ──────────────────────────────────
  {
    id: "tg_ctf_01", nameEs: "IP/Geo/Whois (Telegram)", nameEn: "IP/Geo/Whois (Telegram)",
    file: "bots/ctf-osint/tg_01_ip_geo_whois.py", category: "ctf-osint",
    descEs: "Geolocalización de IPs, búsqueda Whois y análisis de rangos CIDR.",
    descEn: "IP geolocation, Whois lookup and CIDR range analysis.",
    commands: ["/start", "/ip <IP>", "/whois <dominio>", "/cidr <rango>"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "/ip 8.8.8.8 → geolocalización | /whois google.com → registro WHOIS",
    usageEn: "/ip 8.8.8.8 → geolocation | /whois google.com → WHOIS record",
    tags: ["CTF", "OSINT", "IP", "Whois", "geolocalización"],
  },
  {
    id: "tg_ctf_02", nameEs: "Reconocimiento DNS (Telegram)", nameEn: "DNS Recon (Telegram)",
    file: "bots/ctf-osint/tg_02_dns_recon.py", category: "ctf-osint",
    descEs: "Reconocimiento DNS completo: A, MX, NS, TXT, SPF, DKIM, subdomains.",
    descEn: "Full DNS reconnaissance: A, MX, NS, TXT, SPF, DKIM, subdomains.",
    commands: ["/start", "/dns <dominio>", "/mx <dominio>", "/sub <dominio>"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "/dns example.com → todos los registros | /mx gmail.com → servidores de correo",
    usageEn: "/dns example.com → all records | /mx gmail.com → mail servers",
    tags: ["CTF", "OSINT", "DNS", "reconocimiento"],
  },
  {
    id: "tg_ctf_03", nameEs: "Suite de Hashes (Telegram)", nameEn: "Hash Suite (Telegram)",
    file: "bots/ctf-osint/tg_03_hash_suite.py", category: "ctf-osint",
    descEs: "Calcula MD5/SHA1/SHA256/SHA512, identifica tipos de hash y verifica integridad.",
    descEn: "Calculates MD5/SHA1/SHA256/SHA512, identifies hash types and verifies integrity.",
    commands: ["/start", "/hash <texto>", "/identify <hash>", "/crack <hash>"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "/hash Hola → hashes | /identify d8e8fca2dc0f896fd7cb4cb0031ba249 → tipo",
    usageEn: "/hash Hello → hashes | /identify d8e8fca2dc0f896fd7cb4cb0031ba249 → type",
    tags: ["CTF", "hashes", "MD5", "SHA", "criptografía"],
  },
  {
    id: "tg_ctf_04", nameEs: "Navaja de Encodings (Telegram)", nameEn: "Encoding Knife (Telegram)",
    file: "bots/ctf-osint/tg_04_encoding_knife.py", category: "ctf-osint",
    descEs: "Base64/32/16, ROT13/47, URL encode/decode, Morse, hexadecimal, binario.",
    descEn: "Base64/32/16, ROT13/47, URL encode/decode, Morse, hexadecimal, binary.",
    commands: ["/start", "/b64e <texto>", "/b64d <b64>", "/rot13 <texto>", "/morse <texto>"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "/b64e Hola → SGVsb G8= | /rot13 Uryyb → Hello",
    usageEn: "/b64e Hello → SGVsbG8= | /rot13 Uryyb → Hello",
    tags: ["CTF", "encoding", "Base64", "ROT13", "Morse"],
  },
  {
    id: "tg_ctf_05", nameEs: "Constructor SQLi (Telegram)", nameEn: "SQLi Builder (Telegram)",
    file: "bots/ctf-osint/tg_05_sqli_builder.py", category: "ctf-osint",
    descEs: "Genera y analiza payloads de inyección SQL para CTF y práctica controlada.",
    descEn: "Generates and analyzes SQL injection payloads for CTF and controlled practice.",
    commands: ["/start", "/sqli <tipo>", "/explain <payload>", "/bypass <filtro>"],
    envVars: ["TELEGRAM_BOT_TOKEN"],
    usageEs: "/sqli union → payload UNION | /explain 1' OR '1'='1 → análisis",
    usageEn: "/sqli union → UNION payload | /explain 1' OR '1'='1 → analysis",
    tags: ["CTF", "SQLi", "inyección SQL", "pentesting educativo"],
  },
  // ── WHATSAPP ─────────────────────────────────────────────
  {
    id: "wa_webhook", nameEs: "Webhook Básico WhatsApp", nameEn: "WhatsApp Basic Webhook",
    file: "bots/whatsapp/webhook_basic.py", category: "whatsapp",
    descEs: "Webhook Flask mínimo para recibir y responder mensajes de WhatsApp.",
    descEn: "Minimal Flask webhook to receive and reply to WhatsApp messages.",
    commands: ["Cualquier mensaje de texto"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "Requiere webhook público (ngrok). Enviá un mensaje desde WhatsApp.",
    usageEn: "Requires public webhook (ngrok). Send a message from WhatsApp.",
    tags: ["básico", "webhook", "Flask"],
  },
  {
    id: "wa_chatgpt", nameEs: "Bot con ChatGPT (WA)", nameEn: "ChatGPT Bot (WA)",
    file: "bots/whatsapp/chatgpt_integration.py", category: "whatsapp",
    descEs: "Integra GPT-3.5/4 para responder mensajes de WhatsApp con IA.",
    descEn: "Integrates GPT-3.5/4 to reply to WhatsApp messages with AI.",
    commands: ["Cualquier texto"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Enviá cualquier mensaje — ChatGPT responde automáticamente.",
    usageEn: "Send any message — ChatGPT replies automatically.",
    tags: ["IA", "ChatGPT", "OpenAI"],
  },
  {
    id: "wa_commands", nameEs: "Enrutador de Comandos (WA)", nameEn: "Command Router (WA)",
    file: "bots/whatsapp/command_router.py", category: "whatsapp",
    descEs: "Enruta comandos !cmd a handlers separados con registro de uso.",
    descEn: "Routes !cmd commands to separate handlers with usage logging.",
    commands: ["!help", "!info", "!ping", "!hora"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "Enviá !help para ver los comandos disponibles.",
    usageEn: "Send !help to see available commands.",
    tags: ["comandos", "enrutador"],
  },
  {
    id: "wa_media", nameEs: "Bot de Multimedia (WA)", nameEn: "Media Messages Bot (WA)",
    file: "bots/whatsapp/media_messages.py", category: "whatsapp",
    descEs: "Envía y recibe imágenes, audio, video y documentos por WhatsApp.",
    descEn: "Sends and receives images, audio, video and documents via WhatsApp.",
    commands: ["!imagen", "!audio", "!sticker"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "Enviá !imagen para recibir una imagen de ejemplo.",
    usageEn: "Send !imagen for a sample image reply.",
    tags: ["multimedia", "imágenes", "audio", "video"],
  },
  {
    id: "wa_sqlite", nameEs: "Bot con SQLite (WA)", nameEn: "SQLite Bot (WA)",
    file: "bots/whatsapp/sqlite_database.py", category: "whatsapp",
    descEs: "Persiste preferencias y datos de usuarios de WhatsApp en SQLite.",
    descEn: "Persists WhatsApp user preferences and data in SQLite.",
    commands: ["!guardar <k> <v>", "!obtener <k>", "!mis-datos"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!guardar nombre Juan → !obtener nombre → Juan",
    usageEn: "!guardar name John → !obtener name → John",
    tags: ["sqlite", "base de datos", "persistencia"],
  },
  {
    id: "wa_group", nameEs: "Bot Multiusuario Grupos (WA)", nameEn: "Group Multiuser Bot (WA)",
    file: "bots/whatsapp/group_multiuser.py", category: "whatsapp",
    descEs: "Maneja contextos separados por usuario en grupos de WhatsApp.",
    descEn: "Handles separate user contexts in WhatsApp groups.",
    commands: ["!yo", "!grupo", "!stats"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!yo → info de tu sesión | !stats → estadísticas del grupo",
    usageEn: "!yo → your session info | !stats → group statistics",
    tags: ["grupos", "multiusuario", "contexto"],
  },
  {
    id: "wa_scheduler", nameEs: "Programador APScheduler (WA)", nameEn: "APScheduler Bot (WA)",
    file: "bots/whatsapp/scheduler_apscheduler.py", category: "whatsapp",
    descEs: "Programa mensajes y notificaciones automáticas con APScheduler.",
    descEn: "Schedules messages and automatic notifications with APScheduler.",
    commands: ["!recordar <min> <msg>", "!mis-recordatorios", "!cancelar <id>"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!recordar 30 Tomar agua → te avisa en 30 minutos.",
    usageEn: "!recordar 30 Drink water → reminds you in 30 minutes.",
    tags: ["programador", "recordatorios", "APScheduler"],
  },
  {
    id: "wa_lang", nameEs: "Detección de Idioma (WA)", nameEn: "Language Detection Bot (WA)",
    file: "bots/whatsapp/auto_language_detect.py", category: "whatsapp",
    descEs: "Detecta automáticamente el idioma del mensaje y responde en el mismo idioma.",
    descEn: "Auto-detects message language and replies in the same language.",
    commands: ["Cualquier texto en cualquier idioma"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "Escribí en cualquier idioma — el bot detecta y responde igual.",
    usageEn: "Write in any language — the bot detects and replies the same.",
    tags: ["idioma", "NLP", "multilingüe"],
  },
  {
    id: "wa_agent_openai", nameEs: "Agente OpenAI Persistente (WA)", nameEn: "Persistent OpenAI Agent (WA)",
    file: "bots/whatsapp/agent_openai_persistent.py", category: "whatsapp",
    descEs: "Agente GPT con memoria persistente por usuario entre sesiones.",
    descEn: "GPT agent with persistent per-user memory across sessions.",
    commands: ["Cualquier texto", "!reset", "!historia"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN", "OPENAI_API_KEY"],
    usageEs: "Conversá con el bot — recuerda el contexto entre sesiones.",
    usageEn: "Chat with the bot — it remembers context across sessions.",
    tags: ["IA", "OpenAI", "memoria persistente", "agente"],
  },
  {
    id: "wa_orders", nameEs: "Rastreador de Pedidos (WA)", nameEn: "Order Tracker Bot (WA)",
    file: "bots/whatsapp/order_tracker.py", category: "whatsapp",
    descEs: "Sistema de seguimiento de pedidos con estados y notificaciones automáticas.",
    descEn: "Order tracking system with states and automatic notifications.",
    commands: ["!pedido <id>", "!mis-pedidos", "!nuevo-pedido"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!nuevo-pedido → crear pedido | !pedido #123 → seguimiento",
    usageEn: "!nuevo-pedido → create order | !pedido #123 → tracking",
    tags: ["comercio", "pedidos", "tracking", "notificaciones"],
  },
  // ── CTF / OSINT WHATSAPP ──────────────────────────────────
  {
    id: "wa_ctf_01", nameEs: "IP/Geo (WhatsApp)", nameEn: "IP/Geo (WhatsApp)",
    file: "bots/ctf-osint/wa_01_ip_geo.py", category: "ctf-osint",
    descEs: "Geolocalización de IPs y rangos de red vía WhatsApp.",
    descEn: "IP geolocation and network range lookup via WhatsApp.",
    commands: ["!ip <IP>", "!geo <IP>", "!asn <IP>"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!ip 8.8.8.8 → ubicación, proveedor y ASN",
    usageEn: "!ip 8.8.8.8 → location, provider and ASN",
    tags: ["CTF", "OSINT", "IP", "geolocalización"],
  },
  {
    id: "wa_ctf_02", nameEs: "Headers y Tecnologías (WhatsApp)", nameEn: "Headers & Tech (WhatsApp)",
    file: "bots/ctf-osint/wa_02_headers_tech.py", category: "ctf-osint",
    descEs: "Analiza headers HTTP y detecta tecnologías de sitios web.",
    descEn: "Analyzes HTTP headers and detects website technologies.",
    commands: ["!headers <url>", "!tech <url>", "!ssl <dominio>"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!headers https://ejemplo.com → todos los headers HTTP",
    usageEn: "!headers https://example.com → all HTTP headers",
    tags: ["CTF", "OSINT", "headers HTTP", "web fingerprinting"],
  },
  {
    id: "wa_ctf_03", nameEs: "Suite de Hashes (WhatsApp)", nameEn: "Hash Suite (WhatsApp)",
    file: "bots/ctf-osint/wa_03_hash_suite.py", category: "ctf-osint",
    descEs: "Calcula e identifica hashes MD5/SHA. Compatible con WhatsApp.",
    descEn: "Calculates and identifies MD5/SHA hashes. WhatsApp compatible.",
    commands: ["!hash <texto>", "!id <hash>", "!sha256 <texto>"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!hash Hola → md5, sha1, sha256, sha512",
    usageEn: "!hash Hello → md5, sha1, sha256, sha512",
    tags: ["CTF", "hashes", "MD5", "SHA"],
  },
  {
    id: "wa_ctf_04", nameEs: "Encodings (WhatsApp)", nameEn: "Encodings (WhatsApp)",
    file: "bots/ctf-osint/wa_04_encoding.py", category: "ctf-osint",
    descEs: "Base64, ROT13, URL encoding y Morse vía WhatsApp.",
    descEn: "Base64, ROT13, URL encoding and Morse via WhatsApp.",
    commands: ["!b64 <texto>", "!db64 <b64>", "!rot13 <texto>", "!morse <texto>"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!b64 Hola → SGVsb G8= | !rot13 Uryyb → Hello",
    usageEn: "!b64 Hello → SGVsbG8= | !rot13 Uryyb → Hello",
    tags: ["CTF", "encoding", "Base64", "ROT13"],
  },
  {
    id: "wa_ctf_05", nameEs: "Kit CTF Completo (WhatsApp)", nameEn: "CTF Full Toolkit (WhatsApp)",
    file: "bots/ctf-osint/wa_05_ctf_toolkit.py", category: "ctf-osint",
    descEs: "Toolkit CTF completo: hashes, encodings, SQL, DNS y más en un solo bot.",
    descEn: "Complete CTF toolkit: hashes, encodings, SQL, DNS and more in one bot.",
    commands: ["!help", "!hash", "!b64", "!dns", "!ip", "!sqli", "!xss"],
    envVars: ["WHATSAPP_API_KEY", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN", "WHATSAPP_ACCESS_TOKEN"],
    usageEs: "!help → lista completa de herramientas disponibles",
    usageEn: "!help → full list of available tools",
    tags: ["CTF", "OSINT", "all-in-one", "toolkit completo"],
  },
  // ── UTILIDAD ──────────────────────────────────────────────
  {
    id: "watchdog", nameEs: "Watchdog 24/7", nameEn: "Watchdog 24/7",
    file: "watchdog_bot.py", category: "utility",
    descEs: "Reinicia automáticamente cualquier bot si se cae. Notificaciones opcionales por Telegram.",
    descEn: "Automatically restarts any bot if it crashes. Optional Telegram notifications.",
    commands: ["(No tiene comandos — corre en background)"],
    envVars: ["BOT_SCRIPT", "RESTART_DELAY", "MAX_RESTARTS_PER_HOUR"],
    usageEs: "Configurá BOT_SCRIPT=bots/telegram/echo_bot.py en .env y ejecutá.",
    usageEn: "Set BOT_SCRIPT=bots/telegram/echo_bot.py in .env and run.",
    tags: ["utilidad", "watchdog", "24/7", "supervisor"],
  },
];

export function getBotById(id: string): BotEntry | undefined {
  return BOT_CATALOG.find((b) => b.id === id);
}

export function getBotsByCategory(category: BotEntry["category"]): BotEntry[] {
  return BOT_CATALOG.filter((b) => b.category === category);
}
