import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { dataPath, PROJECT_ROOT } from "./data-dir";
import { logger } from "./logger";

const TOKENS_FILE = dataPath("tokens.json");
const ENV_FILE = resolve(PROJECT_ROOT, ".env");

export const TOKEN_KEYS = [
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_OWNER_ID",
  "WHATSAPP_API_KEY",
  "WHATSAPP_PHONE_NUMBER_ID",
  "WHATSAPP_VERIFY_TOKEN",
  "WHATSAPP_ACCESS_TOKEN",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "GEMINI_API_KEY",
] as const;

export type TokenKey = (typeof TOKEN_KEYS)[number];

export type TokensMap = Partial<Record<TokenKey, string>>;

function readJson(): TokensMap {
  if (!existsSync(TOKENS_FILE)) return {};
  try {
    const raw = JSON.parse(readFileSync(TOKENS_FILE, "utf-8"));
    const out: TokensMap = {};
    for (const k of TOKEN_KEYS) {
      if (typeof raw?.[k] === "string") out[k] = raw[k];
    }
    return out;
  } catch {
    return {};
  }
}

function writeJson(t: TokensMap): void {
  writeFileSync(TOKENS_FILE, JSON.stringify(t, null, 2), "utf-8");
}

function parseEnvFile(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function syncToEnvFile(tokens: TokensMap): void {
  const existing = existsSync(ENV_FILE) ? parseEnvFile(readFileSync(ENV_FILE, "utf-8")) : {};
  const merged: Record<string, string> = { ...existing };
  for (const k of TOKEN_KEYS) {
    const v = tokens[k];
    if (v && v.length > 0) merged[k] = v;
    else delete merged[k];
  }
  const lines = [
    "# Auto-generated by Plantillas de bots admin panel.",
    "# Edit tokens through the panel; this file is overwritten on save.",
    "",
  ];
  for (const [k, v] of Object.entries(merged)) {
    const escaped = v.includes(" ") || v.includes("#") ? `"${v.replace(/"/g, '\\"')}"` : v;
    lines.push(`${k}=${escaped}`);
  }
  writeFileSync(ENV_FILE, lines.join("\n") + "\n", "utf-8");
  logger.info({ envFile: ENV_FILE, count: Object.keys(merged).length }, "Synced tokens to .env");
}

export function getTokens(): TokensMap {
  return readJson();
}

export function getTokensMasked(): TokensMap {
  const t = readJson();
  const out: TokensMap = {};
  for (const k of TOKEN_KEYS) {
    const v = t[k];
    if (!v) continue;
    if (v.length <= 6) out[k] = "•".repeat(v.length);
    else out[k] = `${v.slice(0, 4)}${"•".repeat(Math.max(4, v.length - 8))}${v.slice(-4)}`;
  }
  return out;
}

export function saveTokens(input: TokensMap): TokensMap {
  const current = readJson();
  const next: TokensMap = { ...current };
  for (const k of TOKEN_KEYS) {
    const v = input[k];
    if (v === undefined) continue;
    if (v === "") delete next[k];
    else next[k] = String(v).trim();
  }
  writeJson(next);
  syncToEnvFile(next);
  return next;
}
